<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net481</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="DevExpress.Data.v20.2"></Reference>
    <Reference Include="DevExpress.Data.Desktop.v20.2"></Reference>
    <Reference Include="DevExpress.Utils.v20.2"></Reference>
    <Reference Include="DevExpress.Utils.v20.2.UI"></Reference>
    <Reference Include="DevExpress.XtraBars.v20.2"></Reference>
    <Reference Include="DevExpress.XtraEditors.v20.2"></Reference>
    <Reference Include="DevExpress.XtraLayout.v20.2"></Reference>
    <Reference Include="DevExpress.XtraVerticalGrid.v20.2"></Reference>
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Properties\licenses.licx" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\StrumentiMusicali.Core\StrumentiMusicali.Core.csproj" />
    <ProjectReference Include="..\StrumentiMusicaliApp\StrumentiMusicali.App.csproj" />
    <ProjectReference Include="..\StrumentiMusicaliSql\StrumentiMusicali.Library.csproj" />
  </ItemGroup>
</Project>