// <auto-generated />
namespace StrumentiMusicali.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class RegistratoreDiCassa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RegistratoreDiCassa));
        
        string IMigrationMetadata.Id
        {
            get { return "202109241447088_RegistratoreDiCassa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
