// <auto-generated />
namespace StrumentiMusicali.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SottoScorta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SottoScorta));
        
        string IMigrationMetadata.Id
        {
            get { return "202104301359509_SottoScorta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
