// <auto-generated />
namespace StrumentiMusicali.Library.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ImportWeb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ImportWeb));
        
        string IMigrationMetadata.Id
        {
            get { return "202205041301246_ImportWeb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
