namespace StrumentiMusicali.Library.Migrations
{
    using StrumentiMusicali.Library.Entity.Articoli;
    using StrumentiMusicali.Library.Model;
    using System;
    using System.Data.Entity.Migrations;

    internal sealed class Configuration : DbMigrationsConfiguration<StrumentiMusicali.Library.Model.ModelSm>
	{
		public Configuration()
		{
			AutomaticMigrationsEnabled = true;
			AutomaticMigrationDataLossAllowed = true;
		}

		protected override void Seed(StrumentiMusicali.Library.Model.ModelSm context)
		{
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method
            //  to avoid creating duplicate seed data.

            //InitCategories(context);
            //InitTipiPagamenti(context);
        }

        private void InitTipiPagamenti(ModelSm context)
        {
            context.TipiPagamentoScontrino.AddOrUpdate(

                pag => new { pag.Codice, pag.Descrizione }
                                ,



            new Entity.TipiPagamentoScontrino() { Codice = 1, Descrizione = "Pagamento in Contanti" },
            new Entity.TipiPagamentoScontrino() { Codice = 2, Descrizione = "Pagamento con Assegno" },
            new Entity.TipiPagamentoScontrino() { Codice = 3, Descrizione = "Pagamento con Credito" },
            new Entity.TipiPagamentoScontrino() { Codice = 4, Descrizione = "Pagamento con Carta di credito" },
            new Entity.TipiPagamentoScontrino() { Codice = 5, Descrizione = "Pagamento in Corrispettivi non riscossi" },
            new Entity.TipiPagamentoScontrino() { Codice = 54, Descrizione = "Pagamento con Bancomat" }
            );


        }

        private static void InitCategories(Model.ModelSm context)
		{

			context.Categorie.AddOrUpdate(categoria => new { categoria.Nome, categoria.Reparto, categoria.Codice, categoria.CategoriaCondivisaCon }
								,



				new Categoria() { Nome = "Synth a Tastiera", Reparto = "Tastiere", Codice = 1, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Workstation a Tastiera", Reparto = "Tastiere", Codice = 2, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Digital / Stage Piano", Reparto = "Tastiere", Codice = 4, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Master Keyboard / Controller Midi", Reparto = "Tastiere", Codice = 5, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Arranger a Tastiera", Reparto = "Tastiere", Codice = 16, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Expander Rack", Reparto = "Tastiere", Codice = 3, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Campionatori / Groove Box", Reparto = "Tastiere", Codice = 14, CategoriaCondivisaCon = " Home & Studio Recording, DJ Equipment" },
			new Categoria() { Nome = "Librerie Suoni", Reparto = "Tastiere", Codice = 15, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Pianoforti Acustici", Reparto = "Tastiere", Codice = 12, CategoriaCondivisaCon = " Strumenti a Corda" },
			new Categoria() { Nome = "Organi / Hammond e Cloni", Reparto = "Tastiere", Codice = 6, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Fisarmoniche", Reparto = "Tastiere", Codice = 141, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Amplificatori per Tastiera", Reparto = "Tastiere", Codice = 11, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Pedali per Tastiera e Synth", Reparto = "Tastiere", Codice = 7, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Stand per Tastiera", Reparto = "Tastiere", Codice = 8, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Sgabelli e Panche", Reparto = "Tastiere", Codice = 50, CategoriaCondivisaCon = " Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Accordatori / Metronomi", Reparto = "Tastiere", Codice = 28, CategoriaCondivisaCon = " Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Leggii e Altri Supporti", Reparto = "Tastiere", Codice = 302, CategoriaCondivisaCon = " Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Custodie per Tastiera", Reparto = "Tastiere", Codice = 9, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Altri Accessori per Tastiera", Reparto = "Tastiere", Codice = 10, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Cavi Audio e Adattatori", Reparto = "Tastiere", Codice = 83, CategoriaCondivisaCon = " Chitarre, Bassi, Home & Studio Recording, Live Equipment, DJ Equipment" },
			new Categoria() { Nome = "Chitarre Elettriche", Reparto = "Chitarre", Codice = 17, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Chitarre Semiacustiche", Reparto = "Chitarre", Codice = 18, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Chitarre Acustiche", Reparto = "Chitarre", Codice = 19, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Chitarre Classiche", Reparto = "Chitarre", Codice = 20, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Mandolini / Ukulele / Banjo", Reparto = "Chitarre", Codice = 68, CategoriaCondivisaCon = " Strumenti a Corda" },
			new Categoria() { Nome = "Amplificatori - Combo per Chitarra", Reparto = "Chitarre", Codice = 21, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Amplificatori - Testata / Cassa per Chitarra", Reparto = "Chitarre", Codice = 22, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Valvole per Amplificatori", Reparto = "Chitarre", Codice = 250, CategoriaCondivisaCon = " Bassi" },
			new Categoria() { Nome = "Pedalini Singoli per Chitarra", Reparto = "Chitarre", Codice = 25, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Pedaliere Multieffetto per Chitarra", Reparto = "Chitarre", Codice = 24, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Effetti a Rack per Chitarra", Reparto = "Chitarre", Codice = 23, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Accordatori / Metronomi", Reparto = "Chitarre", Codice = 28, CategoriaCondivisaCon = " Tastiere, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Corpi / Body per Chitarra", Reparto = "Chitarre", Codice = 255, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Manici per Chitarra", Reparto = "Chitarre", Codice = 254, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Pick-up per Chitarra", Reparto = "Chitarre", Codice = 252, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Battipenna per Chitarra", Reparto = "Chitarre", Codice = 251, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Manopole / Potenziometri", Reparto = "Chitarre", Codice = 309, CategoriaCondivisaCon = " Bassi" },
			new Categoria() { Nome = "Ponti / Tremoli per Chitarra", Reparto = "Chitarre", Codice = 257, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Meccaniche per Chitarra", Reparto = "Chitarre", Codice = 256, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Corde per Chitarra", Reparto = "Chitarre", Codice = 253, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Tracolle per Chitarra e Basso", Reparto = "Chitarre", Codice = 306, CategoriaCondivisaCon = " Bassi" },
			new Categoria() { Nome = "Plettri per chitarra e Basso", Reparto = "Chitarre", Codice = 258, CategoriaCondivisaCon = " Bassi, Merchandising" },
			new Categoria() { Nome = "Custodie per Chitarra", Reparto = "Chitarre", Codice = 26, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Stand per Chitarra e Basso", Reparto = "Chitarre", Codice = 304, CategoriaCondivisaCon = " Bassi" },
			new Categoria() { Nome = "Sgabelli e Panche", Reparto = "Chitarre", Codice = 50, CategoriaCondivisaCon = " Tastiere, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Leggii e Altri Supporti", Reparto = "Chitarre", Codice = 302, CategoriaCondivisaCon = " Tastiere, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Altri Accessori per Chitarra", Reparto = "Chitarre", Codice = 27, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Cavi Audio e Adattatori", Reparto = "Chitarre", Codice = 83, CategoriaCondivisaCon = " Tastiere, Bassi, Home & Studio Recording, Live Equipment, DJ Equipment" },
			new Categoria() { Nome = "Bassi Elettrici 4 corde", Reparto = "Bassi", Codice = 29, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Bassi Elettrici 5/6/+ corde", Reparto = "Bassi", Codice = 30, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Bassi Acustici", Reparto = "Bassi", Codice = 31, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Amplificatori - Combo per Basso", Reparto = "Bassi", Codice = 32, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Amplificatori - Testata / Cassa per Basso", Reparto = "Bassi", Codice = 33, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Valvole per Amplificatori", Reparto = "Bassi", Codice = 250, CategoriaCondivisaCon = " Chitarre" },
			new Categoria() { Nome = "Pedalini Singoli per Basso", Reparto = "Bassi", Codice = 36, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Pedaliere Multieffetto per Basso", Reparto = "Bassi", Codice = 35, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Effetti a Rack per Basso", Reparto = "Bassi", Codice = 34, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Accordatori / Metronomi", Reparto = "Bassi", Codice = 28, CategoriaCondivisaCon = " Tastiere, Chitarre, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Corpi / Body per Basso", Reparto = "Bassi", Codice = 263, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Manici per Basso", Reparto = "Bassi", Codice = 262, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Pick-up per Basso", Reparto = "Bassi", Codice = 261, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Battipenna per Basso", Reparto = "Bassi", Codice = 259, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Manopole / Potenziometri", Reparto = "Bassi", Codice = 309, CategoriaCondivisaCon = " Chitarre" },
			new Categoria() { Nome = "Ponti / Tremoli per Basso", Reparto = "Bassi", Codice = 265, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Meccaniche per Basso", Reparto = "Bassi", Codice = 264, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Corde per Basso", Reparto = "Bassi", Codice = 260, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Tracolle per Chitarra e Basso", Reparto = "Bassi", Codice = 306, CategoriaCondivisaCon = " Chitarre" },
			new Categoria() { Nome = "Plettri per chitarra e Basso", Reparto = "Bassi", Codice = 258, CategoriaCondivisaCon = " Chitarre, Merchandising" },
			new Categoria() { Nome = "Custodie per Basso", Reparto = "Bassi", Codice = 37, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Stand per Chitarra e Basso", Reparto = "Bassi", Codice = 304, CategoriaCondivisaCon = " Chitarre" },
			new Categoria() { Nome = "Sgabelli e Panche", Reparto = "Bassi", Codice = 50, CategoriaCondivisaCon = " Tastiere, Chitarre, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Leggii e Altri Supporti", Reparto = "Bassi", Codice = 302, CategoriaCondivisaCon = " Tastiere, Chitarre, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Altri Accessori per Basso", Reparto = "Bassi", Codice = 38, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Cavi Audio e Adattatori", Reparto = "Bassi", Codice = 83, CategoriaCondivisaCon = " Tastiere, Chitarre, Home & Studio Recording, Live Equipment, DJ Equipment" },
			new Categoria() { Nome = "Batterie Acustiche - Set Completi", Reparto = "Batterie / Percussioni", Codice = 40, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Batterie Elettroniche - Set Completi", Reparto = "Batterie / Percussioni", Codice = 41, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Batterie Elettroniche - Moduli / Pad", Reparto = "Batterie / Percussioni", Codice = 269, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Gran Cassa", Reparto = "Batterie / Percussioni", Codice = 145, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Rullanti", Reparto = "Batterie / Percussioni", Codice = 142, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Tom", Reparto = "Batterie / Percussioni", Codice = 143, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Timpani", Reparto = "Batterie / Percussioni", Codice = 144, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Pelli / Cerchi / Ring", Reparto = "Batterie / Percussioni", Codice = 267, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Set di Piatti", Reparto = "Batterie / Percussioni", Codice = 266, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Piatti - HiHat", Reparto = "Batterie / Percussioni", Codice = 45, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Piatti - Crash", Reparto = "Batterie / Percussioni", Codice = 43, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Piatti - Ride", Reparto = "Batterie / Percussioni", Codice = 44, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Piatti - Splash", Reparto = "Batterie / Percussioni", Codice = 46, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Piatti - China e Altri", Reparto = "Batterie / Percussioni", Codice = 47, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Percussioni / Etnici", Reparto = "Batterie / Percussioni", Codice = 42, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Meccaniche / Aste / Supporti", Reparto = "Batterie / Percussioni", Codice = 48, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Pedali per Batteria", Reparto = "Batterie / Percussioni", Codice = 49, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Sgabelli e Panche", Reparto = "Batterie / Percussioni", Codice = 50, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Leggii e Altri Supporti", Reparto = "Batterie / Percussioni", Codice = 302, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Custodie per Batteria", Reparto = "Batterie / Percussioni", Codice = 51, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Bacchette e Spazzole", Reparto = "Batterie / Percussioni", Codice = 268, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Accordatori / Metronomi", Reparto = "Batterie / Percussioni", Codice = 28, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Microfoni per Batteria", Reparto = "Batterie / Percussioni", Codice = 153, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Prodotti per Isolamento Acustico", Reparto = "Batterie / Percussioni", Codice = 77, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Altri Accessori per Batteria", Reparto = "Batterie / Percussioni", Codice = 52, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Sax", Reparto = "Strumenti a Fiato", Codice = 53, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Clarinetti", Reparto = "Strumenti a Fiato", Codice = 54, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Flauti", Reparto = "Strumenti a Fiato", Codice = 55, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Trombe", Reparto = "Strumenti a Fiato", Codice = 56, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Corni / Flicorni", Reparto = "Strumenti a Fiato", Codice = 57, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Tromboni / Bassi Tuba", Reparto = "Strumenti a Fiato", Codice = 58, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Oboi / Fagotti", Reparto = "Strumenti a Fiato", Codice = 59, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Armonica a bocca", Reparto = "Strumenti a Fiato", Codice = 272, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Altri Strumenti a Fiato", Reparto = "Strumenti a Fiato", Codice = 307, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Bocchini e Ance per Legni", Reparto = "Strumenti a Fiato", Codice = 275, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Bocchini per Ottoni", Reparto = "Strumenti a Fiato", Codice = 274, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Sordine", Reparto = "Strumenti a Fiato", Codice = 273, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Legni - Altro / Accessori", Reparto = "Strumenti a Fiato", Codice = 61, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Ottoni - Altro / Accessori", Reparto = "Strumenti a Fiato", Codice = 60, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Custodie per Fiati", Reparto = "Strumenti a Fiato", Codice = 63, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Accordatori / Metronomi", Reparto = "Strumenti a Fiato", Codice = 28, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Sgabelli e Panche", Reparto = "Strumenti a Fiato", Codice = 50, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Leggii e Altri Supporti", Reparto = "Strumenti a Fiato", Codice = 302, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Corda, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Fiati - Altro / Accessori", Reparto = "Strumenti a Fiato", Codice = 62, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Violini / Viole", Reparto = "Strumenti a Corda", Codice = 65, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Violoncelli / Contrabbassi", Reparto = "Strumenti a Corda", Codice = 66, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Mandolini / Ukulele / Banjo", Reparto = "Strumenti a Corda", Codice = 68, CategoriaCondivisaCon = " Chitarre" },
			new Categoria() { Nome = "Arpe / Cetre", Reparto = "Strumenti a Corda", Codice = 276, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Strumenti Silent", Reparto = "Strumenti a Corda", Codice = 69, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Pianoforti Acustici", Reparto = "Strumenti a Corda", Codice = 12, CategoriaCondivisaCon = " Tastiere" },
			new Categoria() { Nome = "Altri Strumenti a Corda", Reparto = "Strumenti a Corda", Codice = 70, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Accessori - Corde", Reparto = "Strumenti a Corda", Codice = 277, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Accessori - Archetti", Reparto = "Strumenti a Corda", Codice = 278, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Custodie per Strumenti a Corda", Reparto = "Strumenti a Corda", Codice = 67, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Accordatori / Metronomi", Reparto = "Strumenti a Corda", Codice = 28, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Sgabelli e Panche", Reparto = "Strumenti a Corda", Codice = 50, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Leggii e Altri Supporti", Reparto = "Strumenti a Corda", Codice = 302, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Altri Accessori per Strumenti a Corda", Reparto = "Strumenti a Corda", Codice = 71, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Mixer Analogici", Reparto = "Home & Studio Recording", Codice = 74, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Mixer Digitali", Reparto = "Home & Studio Recording", Codice = 75, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Equalizzatori", Reparto = "Home & Studio Recording", Codice = 78, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Compressori / Limiter", Reparto = "Home & Studio Recording", Codice = 85, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Preamplificatori", Reparto = "Home & Studio Recording", Codice = 76, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Finali di Potenza", Reparto = "Home & Studio Recording", Codice = 81, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Effetti / Altri Processori di Segnale", Reparto = "Home & Studio Recording", Codice = 79, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Monitor da Studio", Reparto = "Home & Studio Recording", Codice = 72, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Cuffie / Auricolari", Reparto = "Home & Studio Recording", Codice = 80, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Microfoni", Reparto = "Home & Studio Recording", Codice = 98, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Microfoni da Studio", Reparto = "Home & Studio Recording", Codice = 73, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Radiomicrofoni", Reparto = "Home & Studio Recording", Codice = 301, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Workstation PC", Reparto = "Home & Studio Recording", Codice = 147, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Workstation Apple", Reparto = "Home & Studio Recording", Codice = 146, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Schede Audio / Interfacce Midi", Reparto = "Home & Studio Recording", Codice = 84, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Software - Audio / Midi Recording", Reparto = "Home & Studio Recording", Codice = 87, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Software - Virtual Instruments", Reparto = "Home & Studio Recording", Codice = 86, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Software - PlugIn Effects", Reparto = "Home & Studio Recording", Codice = 89, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Registratori Multitraccia", Reparto = "Home & Studio Recording", Codice = 82, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Campionatori / Groove Box", Reparto = "Home & Studio Recording", Codice = 14, CategoriaCondivisaCon = " Tastiere, DJ Equipment" },
			new Categoria() { Nome = "Librerie Suoni", Reparto = "Home & Studio Recording", Codice = 15, CategoriaCondivisaCon = " Tastiere" },
			new Categoria() { Nome = "Player Mp3 / Midi / Karaoke", Reparto = "Home & Studio Recording", Codice = 13, CategoriaCondivisaCon = " Live Equipment, DJ Equipment" },
			new Categoria() { Nome = "Basi Mp3 / Midi / Karaoke", Reparto = "Home & Studio Recording", Codice = 305, CategoriaCondivisaCon = " Live Equipment, DJ Equipment" },
			new Categoria() { Nome = "Accordatori / Metronomi", Reparto = "Home & Studio Recording", Codice = 28, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Live Equipment" },
			new Categoria() { Nome = "Aste Microfoniche", Reparto = "Home & Studio Recording", Codice = 154, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Sgabelli e Panche", Reparto = "Home & Studio Recording", Codice = 50, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Live Equipment" },
			new Categoria() { Nome = "Leggii e Altri Supporti", Reparto = "Home & Studio Recording", Codice = 302, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Live Equipment" },
			new Categoria() { Nome = "Cavi Audio e Adattatori", Reparto = "Home & Studio Recording", Codice = 83, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Live Equipment, DJ Equipment" },
			new Categoria() { Nome = "Prodotti per Isolamento Acustico", Reparto = "Home & Studio Recording", Codice = 77, CategoriaCondivisaCon = " Batterie / Percussioni" },
			new Categoria() { Nome = "Mixer Analogici", Reparto = "Live Equipment", Codice = 74, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Mixer Digitali", Reparto = "Live Equipment", Codice = 75, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Equalizzatori", Reparto = "Live Equipment", Codice = 78, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Compressori / Limiter", Reparto = "Live Equipment", Codice = 85, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Preamplificatori", Reparto = "Live Equipment", Codice = 76, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Finali di Potenza", Reparto = "Live Equipment", Codice = 81, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Effetti / Altri Processori di Segnale", Reparto = "Live Equipment", Codice = 79, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Casse / Monitor Live Attivi", Reparto = "Live Equipment", Codice = 93, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Casse / Monitor Live Passivi", Reparto = "Live Equipment", Codice = 94, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Cuffie / Auricolari", Reparto = "Live Equipment", Codice = 80, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Microfoni", Reparto = "Live Equipment", Codice = 98, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Radiomicrofoni", Reparto = "Live Equipment", Codice = 301, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Player Mp3 / Midi / Karaoke", Reparto = "Live Equipment", Codice = 13, CategoriaCondivisaCon = " Home & Studio Recording, DJ Equipment" },
			new Categoria() { Nome = "Basi Mp3 / Midi / Karaoke", Reparto = "Live Equipment", Codice = 305, CategoriaCondivisaCon = " Home & Studio Recording, DJ Equipment" },
			new Categoria() { Nome = "Accordatori / Metronomi", Reparto = "Live Equipment", Codice = 28, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording" },
			new Categoria() { Nome = "Strutture Rack e Flight Case", Reparto = "Live Equipment", Codice = 97, CategoriaCondivisaCon = " DJ Equipment" },
			new Categoria() { Nome = "Aste Microfoniche", Reparto = "Live Equipment", Codice = 154, CategoriaCondivisaCon = " Home & Studio Recording" },
			new Categoria() { Nome = "Sgabelli e Panche", Reparto = "Live Equipment", Codice = 50, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording" },
			new Categoria() { Nome = "Leggii e Altri Supporti", Reparto = "Live Equipment", Codice = 302, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording" },
			new Categoria() { Nome = "Cavi Audio e Adattatori", Reparto = "Live Equipment", Codice = 83, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Home & Studio Recording, DJ Equipment" },
			new Categoria() { Nome = "Tralicci / Americana / Supporti", Reparto = "Live Equipment", Codice = 308, CategoriaCondivisaCon = " Lighting" },
			new Categoria() { Nome = "Altre Attrezzature Live", Reparto = "Live Equipment", Codice = 155, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "CD Player / Mp3 per DJ", Reparto = "DJ Equipment", Codice = 105, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Consolle / Controller per DJ", Reparto = "DJ Equipment", Codice = 280, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Giradischi e Testine per DJ", Reparto = "DJ Equipment", Codice = 107, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Mixer per DJ", Reparto = "DJ Equipment", Codice = 103, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Campionatori / Groove Box", Reparto = "DJ Equipment", Codice = 14, CategoriaCondivisaCon = " Tastiere, Home & Studio Recording" },
			new Categoria() { Nome = "Cuffie per DJ", Reparto = "DJ Equipment", Codice = 106, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Player Mp3 / Midi / Karaoke", Reparto = "DJ Equipment", Codice = 13, CategoriaCondivisaCon = " Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Basi Mp3 / Midi / Karaoke", Reparto = "DJ Equipment", Codice = 305, CategoriaCondivisaCon = " Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Dischi in Vinile", Reparto = "DJ Equipment", Codice = 113, CategoriaCondivisaCon = " CD / DVD / Didattica" },
			new Categoria() { Nome = "CD Italiani", Reparto = "DJ Equipment", Codice = 111, CategoriaCondivisaCon = " CD / DVD / Didattica" },
			new Categoria() { Nome = "CD Stranieri", Reparto = "DJ Equipment", Codice = 112, CategoriaCondivisaCon = " CD / DVD / Didattica" },
			new Categoria() { Nome = "Borse e Custodie per DJ", Reparto = "DJ Equipment", Codice = 281, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Strutture Rack e Flight Case", Reparto = "DJ Equipment", Codice = 97, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Porta CD / DVD", Reparto = "DJ Equipment", Codice = 282, CategoriaCondivisaCon = " CD / DVD / Didattica" },
			new Categoria() { Nome = "Altri Accessori per DJ", Reparto = "DJ Equipment", Codice = 108, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Cavi Audio e Adattatori", Reparto = "DJ Equipment", Codice = 83, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Home & Studio Recording, Live Equipment" },
			new Categoria() { Nome = "Teste Mobili", Reparto = "Lighting", Codice = 114, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Scanner", Reparto = "Lighting", Codice = 115, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Laser", Reparto = "Lighting", Codice = 116, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Luci Flowers", Reparto = "Lighting", Codice = 296, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Proiettori Luci", Reparto = "Lighting", Codice = 118, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Luci Strobo", Reparto = "Lighting", Codice = 117, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Altri Effetti Luce", Reparto = "Lighting", Codice = 122, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Mixer Luci / Centraline / Dimmer", Reparto = "Lighting", Codice = 123, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Macchine del Fumo / Bolle", Reparto = "Lighting", Codice = 120, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Accessori - Lampade", Reparto = "Lighting", Codice = 297, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Accessori - Gelatine", Reparto = "Lighting", Codice = 300, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Accessori - Ganci / Staffe / Clamp", Reparto = "Lighting", Codice = 298, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Cavi per Lighting", Reparto = "Lighting", Codice = 119, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Tralicci / Americana / Supporti", Reparto = "Lighting", Codice = 308, CategoriaCondivisaCon = " Live Equipment" },
			new Categoria() { Nome = "Altri Accessori per Lighting", Reparto = "Lighting", Codice = 124, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Videoproiettori / Accessori Video", Reparto = "Lighting", Codice = 121, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "CD Italiani", Reparto = "CD / DVD / Didattica", Codice = 111, CategoriaCondivisaCon = " DJ Equipment" },
			new Categoria() { Nome = "CD Stranieri", Reparto = "CD / DVD / Didattica", Codice = 112, CategoriaCondivisaCon = " DJ Equipment" },
			new Categoria() { Nome = "Dischi in Vinile", Reparto = "CD / DVD / Didattica", Codice = 113, CategoriaCondivisaCon = " DJ Equipment" },
			new Categoria() { Nome = "DVD Italiani", Reparto = "CD / DVD / Didattica", Codice = 127, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "DVD Stranieri", Reparto = "CD / DVD / Didattica", Codice = 128, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "DVD / Video Didattici", Reparto = "CD / DVD / Didattica", Codice = 294, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Porta CD / DVD", Reparto = "CD / DVD / Didattica", Codice = 282, CategoriaCondivisaCon = " DJ Equipment" },
			new Categoria() { Nome = "Partiture Rock / Metal / Jazz / Blues", Reparto = "CD / DVD / Didattica", Codice = 130, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Partiture Classica", Reparto = "CD / DVD / Didattica", Codice = 129, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Metodi Studio / Didattica", Reparto = "CD / DVD / Didattica", Codice = 293, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Libri - Biografie", Reparto = "CD / DVD / Didattica", Codice = 132, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Libri - Altro", Reparto = "CD / DVD / Didattica", Codice = 133, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Riviste Musicali", Reparto = "CD / DVD / Didattica", Codice = 295, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Magliette / Felpe", Reparto = "Merchandising", Codice = 283, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Cappellini", Reparto = "Merchandising", Codice = 284, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Altri Prodotti di Abbigliamento", Reparto = "Merchandising", Codice = 285, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Portachiavi / Cinture", Reparto = "Merchandising", Codice = 287, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Spille / Pin Badges", Reparto = "Merchandising", Codice = 288, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Plettri per chitarra e Basso", Reparto = "Merchandising", Codice = 258, CategoriaCondivisaCon = " Chitarre, Bassi" },
			new Categoria() { Nome = "Adesivi / Decalcomanie", Reparto = "Merchandising", Codice = 303, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Tazze / Bicchieri", Reparto = "Merchandising", Codice = 290, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Poster / Bandiere", Reparto = "Merchandising", Codice = 289, CategoriaCondivisaCon = "" },
			new Categoria() { Nome = "Gadget Elettronici", Reparto = "Merchandising", Codice = 286, CategoriaCondivisaCon = "" },


			new Categoria() { Nome = "<Non Specificato>", Reparto = "<Non Specificato>", Codice = -1000, CategoriaCondivisaCon = "" },

			new Categoria() { Nome = "Altri Gadget", Reparto = "Merchandising", Codice = 291, CategoriaCondivisaCon = "" }
			
			
			);
		}
	}
}