namespace StrumentiMusicaliSql.Migrations
{
    using StrumentiMusicaliSql.Entity;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<StrumentiMusicaliSql.Model.ModelSm>
    {
        public Configuration()
        {
        
            AutomaticMigrationsEnabled = true;
        }

        protected override void Seed(StrumentiMusicaliSql.Model.ModelSm context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data.
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Synth a Tastiera", ID = 1, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Workstation a Tastiera", ID = 2, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Digital / Stage Piano", ID = 4, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Master Keyboard / Controller Midi", ID = 5, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Arranger a Tastiera", ID = 16, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Expander Rack", ID = 3, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Campionatori / Groove Box", ID = 14, CategoriaCondivisaCon = " Home & Studio Recording, DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Librerie Suoni", ID = 15, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Pianoforti Acustici", ID = 12, CategoriaCondivisaCon = " Strumenti a Corda" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Organi / Hammond e Cloni", ID = 6, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Fisarmoniche", ID = 141, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Amplificatori per Tastiera", ID = 11, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Pedali per Tastiera e Synth", ID = 7, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Stand per Tastiera", ID = 8, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Sgabelli e Panche", ID = 50, CategoriaCondivisaCon = " Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Accordatori / Metronomi", ID = 28, CategoriaCondivisaCon = " Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Leggii e Altri Supporti", ID = 302, CategoriaCondivisaCon = " Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Custodie per Tastiera", ID = 9, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Altri Accessori per Tastiera", ID = 10, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Tastiere", Categoria = "Cavi Audio e Adattatori", ID = 83, CategoriaCondivisaCon = " Chitarre, Bassi, Home & Studio Recording, Live Equipment, DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Chitarre Elettriche", ID = 17, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Chitarre Semiacustiche", ID = 18, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Chitarre Acustiche", ID = 19, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Chitarre Classiche", ID = 20, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Mandolini / Ukulele / Banjo", ID = 68, CategoriaCondivisaCon = " Strumenti a Corda" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Amplificatori - Combo per Chitarra", ID = 21, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Amplificatori - Testata / Cassa per Chitarra", ID = 22, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Valvole per Amplificatori", ID = 250, CategoriaCondivisaCon = " Bassi" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Pedalini Singoli per Chitarra", ID = 25, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Pedaliere Multieffetto per Chitarra", ID = 24, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Effetti a Rack per Chitarra", ID = 23, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Accordatori / Metronomi", ID = 28, CategoriaCondivisaCon = " Tastiere, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Corpi / Body per Chitarra", ID = 255, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Manici per Chitarra", ID = 254, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Pick-up per Chitarra", ID = 252, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Battipenna per Chitarra", ID = 251, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Manopole / Potenziometri", ID = 309, CategoriaCondivisaCon = " Bassi" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Ponti / Tremoli per Chitarra", ID = 257, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Meccaniche per Chitarra", ID = 256, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Corde per Chitarra", ID = 253, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Tracolle per Chitarra e Basso", ID = 306, CategoriaCondivisaCon = " Bassi" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Plettri per chitarra e Basso", ID = 258, CategoriaCondivisaCon = " Bassi, Merchandising" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Custodie per Chitarra", ID = 26, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Stand per Chitarra e Basso", ID = 304, CategoriaCondivisaCon = " Bassi" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Sgabelli e Panche", ID = 50, CategoriaCondivisaCon = " Tastiere, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Leggii e Altri Supporti", ID = 302, CategoriaCondivisaCon = " Tastiere, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Altri Accessori per Chitarra", ID = 27, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Chitarre", Categoria = "Cavi Audio e Adattatori", ID = 83, CategoriaCondivisaCon = " Tastiere, Bassi, Home & Studio Recording, Live Equipment, DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Bassi Elettrici 4 corde", ID = 29, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Bassi Elettrici 5/6/+ corde", ID = 30, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Bassi Acustici", ID = 31, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Amplificatori - Combo per Basso", ID = 32, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Amplificatori - Testata / Cassa per Basso", ID = 33, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Valvole per Amplificatori", ID = 250, CategoriaCondivisaCon = " Chitarre" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Pedalini Singoli per Basso", ID = 36, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Pedaliere Multieffetto per Basso", ID = 35, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Effetti a Rack per Basso", ID = 34, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Accordatori / Metronomi", ID = 28, CategoriaCondivisaCon = " Tastiere, Chitarre, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Corpi / Body per Basso", ID = 263, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Manici per Basso", ID = 262, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Pick-up per Basso", ID = 261, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Battipenna per Basso", ID = 259, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Manopole / Potenziometri", ID = 309, CategoriaCondivisaCon = " Chitarre" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Ponti / Tremoli per Basso", ID = 265, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Meccaniche per Basso", ID = 264, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Corde per Basso", ID = 260, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Tracolle per Chitarra e Basso", ID = 306, CategoriaCondivisaCon = " Chitarre" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Plettri per chitarra e Basso", ID = 258, CategoriaCondivisaCon = " Chitarre, Merchandising" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Custodie per Basso", ID = 37, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Stand per Chitarra e Basso", ID = 304, CategoriaCondivisaCon = " Chitarre" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Sgabelli e Panche", ID = 50, CategoriaCondivisaCon = " Tastiere, Chitarre, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Leggii e Altri Supporti", ID = 302, CategoriaCondivisaCon = " Tastiere, Chitarre, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Altri Accessori per Basso", ID = 38, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Bassi", Categoria = "Cavi Audio e Adattatori", ID = 83, CategoriaCondivisaCon = " Tastiere, Chitarre, Home & Studio Recording, Live Equipment, DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Batterie Acustiche - Set Completi", ID = 40, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Batterie Elettroniche - Set Completi", ID = 41, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Batterie Elettroniche - Moduli / Pad", ID = 269, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Gran Cassa", ID = 145, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Rullanti", ID = 142, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Tom", ID = 143, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Timpani", ID = 144, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Pelli / Cerchi / Ring", ID = 267, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Set di Piatti", ID = 266, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Piatti - HiHat", ID = 45, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Piatti - Crash", ID = 43, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Piatti - Ride", ID = 44, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Piatti - Splash", ID = 46, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Piatti - China e Altri", ID = 47, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Percussioni / Etnici", ID = 42, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Meccaniche / Aste / Supporti", ID = 48, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Pedali per Batteria", ID = 49, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Sgabelli e Panche", ID = 50, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Leggii e Altri Supporti", ID = 302, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Custodie per Batteria", ID = 51, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Bacchette e Spazzole", ID = 268, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Accordatori / Metronomi", ID = 28, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Microfoni per Batteria", ID = 153, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Prodotti per Isolamento Acustico", ID = 77, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Batterie / Percussioni", Categoria = "Altri Accessori per Batteria", ID = 52, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Sax", ID = 53, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Clarinetti", ID = 54, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Flauti", ID = 55, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Trombe", ID = 56, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Corni / Flicorni", ID = 57, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Tromboni / Bassi Tuba", ID = 58, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Oboi / Fagotti", ID = 59, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Armonica a bocca", ID = 272, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Altri Strumenti a Fiato", ID = 307, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Bocchini e Ance per Legni", ID = 275, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Bocchini per Ottoni", ID = 274, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Sordine", ID = 273, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Legni - Altro / Accessori", ID = 61, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Ottoni - Altro / Accessori", ID = 60, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Custodie per Fiati", ID = 63, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Accordatori / Metronomi", ID = 28, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Sgabelli e Panche", ID = 50, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Leggii e Altri Supporti", ID = 302, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Corda, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Fiato", Categoria = "Fiati - Altro / Accessori", ID = 62, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Violini / Viole", ID = 65, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Violoncelli / Contrabbassi", ID = 66, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Mandolini / Ukulele / Banjo", ID = 68, CategoriaCondivisaCon = " Chitarre" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Arpe / Cetre", ID = 276, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Strumenti Silent", ID = 69, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Pianoforti Acustici", ID = 12, CategoriaCondivisaCon = " Tastiere" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Altri Strumenti a Corda", ID = 70, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Accessori - Corde", ID = 277, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Accessori - Archetti", ID = 278, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Custodie per Strumenti a Corda", ID = 67, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Accordatori / Metronomi", ID = 28, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Sgabelli e Panche", ID = 50, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Leggii e Altri Supporti", ID = 302, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Strumenti a Corda", Categoria = "Altri Accessori per Strumenti a Corda", ID = 71, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Mixer Analogici", ID = 74, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Mixer Digitali", ID = 75, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Equalizzatori", ID = 78, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Compressori / Limiter", ID = 85, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Preamplificatori", ID = 76, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Finali di Potenza", ID = 81, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Effetti / Altri Processori di Segnale", ID = 79, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Monitor da Studio", ID = 72, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Cuffie / Auricolari", ID = 80, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Microfoni", ID = 98, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Microfoni da Studio", ID = 73, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Radiomicrofoni", ID = 301, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Workstation PC", ID = 147, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Workstation Apple", ID = 146, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Schede Audio / Interfacce Midi", ID = 84, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Software - Audio / Midi Recording", ID = 87, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Software - Virtual Instruments", ID = 86, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Software - PlugIn Effects", ID = 89, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Registratori Multitraccia", ID = 82, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Campionatori / Groove Box", ID = 14, CategoriaCondivisaCon = " Tastiere, DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Librerie Suoni", ID = 15, CategoriaCondivisaCon = " Tastiere" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Player Mp3 / Midi / Karaoke", ID = 13, CategoriaCondivisaCon = " Live Equipment, DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Basi Mp3 / Midi / Karaoke", ID = 305, CategoriaCondivisaCon = " Live Equipment, DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Accordatori / Metronomi", ID = 28, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Aste Microfoniche", ID = 154, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Sgabelli e Panche", ID = 50, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Leggii e Altri Supporti", ID = 302, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Cavi Audio e Adattatori", ID = 83, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Live Equipment, DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Home & Studio Recording", Categoria = "Prodotti per Isolamento Acustico", ID = 77, CategoriaCondivisaCon = " Batterie / Percussioni" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Mixer Analogici", ID = 74, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Mixer Digitali", ID = 75, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Equalizzatori", ID = 78, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Compressori / Limiter", ID = 85, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Preamplificatori", ID = 76, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Finali di Potenza", ID = 81, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Effetti / Altri Processori di Segnale", ID = 79, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Casse / Monitor Live Attivi", ID = 93, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Casse / Monitor Live Passivi", ID = 94, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Cuffie / Auricolari", ID = 80, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Microfoni", ID = 98, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Radiomicrofoni", ID = 301, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Player Mp3 / Midi / Karaoke", ID = 13, CategoriaCondivisaCon = " Home & Studio Recording, DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Basi Mp3 / Midi / Karaoke", ID = 305, CategoriaCondivisaCon = " Home & Studio Recording, DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Accordatori / Metronomi", ID = 28, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Strutture Rack e Flight Case", ID = 97, CategoriaCondivisaCon = " DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Aste Microfoniche", ID = 154, CategoriaCondivisaCon = " Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Sgabelli e Panche", ID = 50, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Leggii e Altri Supporti", ID = 302, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Batterie / Percussioni, Strumenti a Fiato, Strumenti a Corda, Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Cavi Audio e Adattatori", ID = 83, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Home & Studio Recording, DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Tralicci / Americana / Supporti", ID = 308, CategoriaCondivisaCon = " Lighting" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Live Equipment", Categoria = "Altre Attrezzature Live", ID = 155, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "CD Player / Mp3 per DJ", ID = 105, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Consolle / Controller per DJ", ID = 280, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Giradischi e Testine per DJ", ID = 107, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Mixer per DJ", ID = 103, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Campionatori / Groove Box", ID = 14, CategoriaCondivisaCon = " Tastiere, Home & Studio Recording" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Cuffie per DJ", ID = 106, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Player Mp3 / Midi / Karaoke", ID = 13, CategoriaCondivisaCon = " Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Basi Mp3 / Midi / Karaoke", ID = 305, CategoriaCondivisaCon = " Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Dischi in Vinile", ID = 113, CategoriaCondivisaCon = " CD / DVD / Didattica" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "CD Italiani", ID = 111, CategoriaCondivisaCon = " CD / DVD / Didattica" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "CD Stranieri", ID = 112, CategoriaCondivisaCon = " CD / DVD / Didattica" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Borse e Custodie per DJ", ID = 281, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Strutture Rack e Flight Case", ID = 97, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Porta CD / DVD", ID = 282, CategoriaCondivisaCon = " CD / DVD / Didattica" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Altri Accessori per DJ", ID = 108, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "DJ Equipment", Categoria = "Cavi Audio e Adattatori", ID = 83, CategoriaCondivisaCon = " Tastiere, Chitarre, Bassi, Home & Studio Recording, Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Teste Mobili", ID = 114, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Scanner", ID = 115, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Laser", ID = 116, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Luci Flowers", ID = 296, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Proiettori Luci", ID = 118, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Luci Strobo", ID = 117, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Altri Effetti Luce", ID = 122, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Mixer Luci / Centraline / Dimmer", ID = 123, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Macchine del Fumo / Bolle", ID = 120, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Accessori - Lampade", ID = 297, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Accessori - Gelatine", ID = 300, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Accessori - Ganci / Staffe / Clamp", ID = 298, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Cavi per Lighting", ID = 119, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Tralicci / Americana / Supporti", ID = 308, CategoriaCondivisaCon = " Live Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Altri Accessori per Lighting", ID = 124, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Lighting", Categoria = "Videoproiettori / Accessori Video", ID = 121, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "CD Italiani", ID = 111, CategoriaCondivisaCon = " DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "CD Stranieri", ID = 112, CategoriaCondivisaCon = " DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "Dischi in Vinile", ID = 113, CategoriaCondivisaCon = " DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "DVD Italiani", ID = 127, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "DVD Stranieri", ID = 128, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "DVD / Video Didattici", ID = 294, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "Porta CD / DVD", ID = 282, CategoriaCondivisaCon = " DJ Equipment" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "Partiture Rock / Metal / Jazz / Blues", ID = 130, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "Partiture Classica", ID = 129, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "Metodi Studio / Didattica", ID = 293, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "Libri - Biografie", ID = 132, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "Libri - Altro", ID = 133, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "CD / DVD / Didattica", Categoria = "Riviste Musicali", ID = 295, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Merchandising", Categoria = "Magliette / Felpe", ID = 283, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Merchandising", Categoria = "Cappellini", ID = 284, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Merchandising", Categoria = "Altri Prodotti di Abbigliamento", ID = 285, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Merchandising", Categoria = "Portachiavi / Cinture", ID = 287, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Merchandising", Categoria = "Spille / Pin Badges", ID = 288, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Merchandising", Categoria = "Plettri per chitarra e Basso", ID = 258, CategoriaCondivisaCon = " Chitarre, Bassi" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Merchandising", Categoria = "Adesivi / Decalcomanie", ID = 303, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Merchandising", Categoria = "Tazze / Bicchieri", ID = 290, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Merchandising", Categoria = "Poster / Bandiere", ID = 289, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Merchandising", Categoria = "Gadget Elettronici", ID = 286, CategoriaCondivisaCon = "" });
            context.Categories.AddOrUpdate(new Categorie { Reparto = "Merchandising", Categoria = "Altri Gadget", ID = 291, CategoriaCondivisaCon = "" });
        }
    }
}
